apiVersion: v2
name: secret-manager
description: External secret management for Kubernetes
type: application
version: 0.2.3
appVersion: "%%APP_VERSION%%"
kubeVersion: ">= 1.11.0"
keywords:
  - kubernetes
  - secret
  - secretstore
  - secret-management
  - vault
  - aws
  - azure
  - crd
home: https://github.com/itscontained/secret-manager
sources:
  - https://hub.docker.com/r/itscontained/secret-manager
  - https://quay.io/repository/itscontained/secret-manager
  - https://github.com/orgs/itscontained/packages/container/secret-manager
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
  - name: mcavoyk
    email: kellinmcavoy@gmail.com
annotations:
  artifacthub.io/links: |
    - name: DockerHub Image
      url: https://hub.docker.com/r/itscontained/secret-manager
    - name: Quay.io Image
      url: https://quay.io/repository/itscontained/secret-manager
    - name: GHCR Image
      url: https://github.com/orgs/itscontained/packages/container/secret-manager
  artifacthub.io/maintainers: |
    - name: Nicholas St. Germain
      email: nick@cajun.pro
    - name: Kellin McAvoy
      email: kellinmcavoy@gmail.com
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: "Basic Install"
  artifacthub.io/images: |
    - name: dockerhub
      image: "itscontained/secret-manager:%%APP_VERSION%%"
      url: "https://hub.docker.com/r/itscontained/secret-manager"
    - name: quay.io
      image: "quay.io/itscontained/secret-manager:%%APP_VERSION%%"
      url: "https://quay.io/repository/itscontained/secret-manager"
    - name: GHCR
      image: "ghcr.io/itscontained/secret-manager:%%APP_VERSION%%"
      url: "https://github.com/orgs/itscontained/packages/container/package/secret-manager"
  artifacthub.io/crds: |
    - kind: ExternalSecret
      version: v1alpha1
      name: externalsecrets.secret-manager.itscontained.io
      displayName: ExternalSecret
      description: An ExternalSecret resource can be created which will ensure a Secret is available with the referenced contents of the external store
    - kind: SecretStore
      version: v1alpha1
      name: secretstores.secret-manager.itscontained.io
      displayName: SecretStore
      description: A SecretStore represents a secure external location for storing secrets, which can be referenced as part of `storeRef` fields
    - kind: ClusterSecretStore
      version: v1alpha1
      name: clustersecretstores.secret-manager.itscontained.io
      displayName: ClusterSecretStore
      description: A ClusterSecretStore represents a secure external location for storing secrets, which can be referenced as part of `storeRef` fields
  artifacthub.io/crdsExamples: |
    - apiVersion: secret-manager.itscontained.io/v1alpha1
      kind: ExternalSecret
      metadata:
        name: hello-service
        namespace: example-ns
      spec:
        storeRef:
          name: vault
        data:
        - secretKey: password
          remoteRef:
            name: teamA/hello-service
            property: serviceBapiKey
    - apiVersion: secret-manager.itscontained.io/v1alpha1
      kind: SecretStore
      metadata:
        name: vault
        namespace: example-ns
      spec:
        vault:
          server: "https://vault.example.com"
          path: secret
          auth:
            kubernetes:
              mountPath: kubernetes
              role: example-role
              secretRef:
                name: vault-secret
    - apiVersion: secret-manager.itscontained.io/v1alpha1
      kind: ClusterSecretStore
      metadata:
        name: vault
      spec:
        vault:
          server: "https://vault.example.com"
          path: secret
          auth:
            kubernetes:
              mountPath: kubernetes
              role: example-role
              secretRef:
                name: vault-secret
